# Generated by Django 3.1.5 on 2021-01-29 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('state_abbr', models.CharField(blank=True, max_length=24)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('date_of_birth', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.statesmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_user',
            },
        ),
    ]
