# Generated by Django 3.1.5 on 2021-01-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statesmodel',
            name='cod_uf',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statesmodel',
            name='state_abbr',
            field=models.CharField(max_length=24),
        ),
    ]
