# Generated by Django 3.1.5 on 2021-03-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='district',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='street',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
