# Generated by Django 3.1.5 on 2021-06-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210629_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('operation_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venda')], max_length=8)),
                ('operation_class', models.CharField(choices=[('day_trade', 'DayTrade'), ('normal', 'Normal')], max_length=9)),
                ('ticker', models.CharField(max_length=50)),
                ('ticker_type', models.CharField(choices=[('stock', 'Ações'), ('fiis', 'Fundos Imobiliários'), ('bdr', 'BDR')], max_length=5)),
                ('units', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unitary_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency_code', models.CharField(max_length=50)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.brokermodel')),
            ],
            options={
                'db_table': 'financial_operation',
            },
        ),
    ]
