# Generated by Django 3.1.5 on 2021-06-30 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_financialoperation_profile"),
    ]

    operations = [
        migrations.RenameModel(old_name="FinancialOperation", new_name="FinancialOperationModel",),
        migrations.CreateModel(
            name="ProcessedIRPFModel",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("reference_year", models.IntegerField()),
                (
                    "processing_datetime",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.profilemodel"),
                ),
            ],
            options={"db_table": "processed_irpf",},
        ),
    ]
