# Generated by Django 3.1.5 on 2021-02-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210216_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='age',
        ),
    ]
