# Generated by Django 3.0.5 on 2020-04-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiareceita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaoviagem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
