name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Run tests
      - name: Install dependencies for Testing
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt --no-cache-dir ; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt --no-cache-dir ; fi
      
      - name: Test with pytest
      run: pytest --cov=./ --cov-report=xml

      # Deploy Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "simplecapp"
          heroku_email: "gustavoronconi95@gmail.com"