name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      SECRET_KEY: "apenas_test_dart"
      POSTGREES_PORT: 5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11"

      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install dependencies for Testing
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt --no-cache-dir ; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt --no-cache-dir ; fi

      # Run Migrations
      - name: Run migrations
        run: python manage.py migrate

      # Run tests
      - name: Test with pytest
        run: python manage.py test

      # Deploy Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "simplecapp"
          heroku_email: "gustavoronconi95@gmail.com"
